<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- 测试项目放在游戏项目目录下面，避免游戏项目把测试代码也编译进去。 -->
        <Compile Remove="Console_RPG.Tests/**/*.cs" />
        <None Remove="Console_RPG.Tests/**/*.cs" />
    </ItemGroup>

</Project>
